spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: gpt-benchmark-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  data:
    redis:
      host: localhost
      port: 6379

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
  queue: gpt-queue

kafka:
  topic: gpt-prompt-topic

hadoop:
  hdfs:
    uri: hdfs://localhost:9000
